// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import TableController from "./table_controller"
application.register("table", TableController)

import ZfController from "./zf_controller"
application.register("zf", ZfController)
