// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TableController from "./table_controller"
application.register("table", TableController)

import ZfController from "./zf_controller"
application.register("zf", ZfController)
