 # docker-compose.yml Works locally for M1

  version: "3.8"
  networks:
    backend:
    frontend:
    selenium:
  services:
    db:
      image: postgres:14.2-alpine
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      networks:
        - backend
    redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
      networks:
        - backend
    chrome_server:
      image: seleniarm/standalone-chromium
      volumes:
        - /dev/shm:/dev/shm
      networks:
        - selenium
    app:
      platform: linux/amd64
      build: .
      tty: true
      volumes:
        - .:/workdir
      working_dir: /workdir
      environment:
        DB: postgresql
        DB_HOST: db
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        BUNDLE_GEMFILE: /workdir/Gemfile
        SELENIUM_REMOTE_URL: http://chrome_server:4444/wd/hub
      # command: bash -c "bundle exec rails s -p 8080 -b '0.0.0.0'"
      command: >
        bash -c "bundle install &&
                 yarn &&
                 yarn build &&
                 bundle exec rails s -p 8080 -b 0.0.0.0"
      networks:
        - backend
        - frontend
        - selenium
      ports:
        - "8080:8080"
      depends_on:
        - db
        - redis
        - chrome_server