 # docker-compose.yml Works locally for M1

  version: "3.8"
  networks:
    backend:
    frontend:
  services:
    db:
      image: postgres:14.2-alpine
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      networks:
        - backend
    redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
      networks:
        - backend
    app:
      platform: linux/amd64
      build: .
      tty: true
      volumes:
        - .:/workdir
      working_dir: /workdir
      environment:
        DB: ${DB_NAME}
        DB_HOST: ${DB_HOST}
        DB_PORT: 5432
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        BUNDLE_GEMFILE: /workdir/Gemfile
      command: >
        bash -c "bundle install &&
                 yarn &&
                 yarn build &&
                 bundle exec rails s -p 8080 -b 0.0.0.0"
      networks:
        - backend
        - frontend 
      ports:
        - "8080:8080"
      depends_on:
        - db
        - redis


