apiVersion: apps/v1
kind: Deployment
metadata:
  name: scam-hitlist-11 # name of the deployment
  labels:
    app: root
    component: scam-hitlist
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: root
      component: scam-hitlist
  template:
    metadata:
      labels:
        app: root
        component: scam-hitlist
    spec:
      containers:
      - name: scam-hitlist
        image: public.ecr.aws/t5u0q4a0/scam-hitlist:latest
        env:
        - name: DB_URL
          value: database-1.cthtpb74ohct.eu-north-1.rds.amazonaws.com
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-creds-2
              key: username 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds-2
              key: password 
        - name: DB_NAME
          value: scam-hitlist
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: db-creds-2
              key: secret-key-base 
        ports:
        - containerPort: 3000
          name: scam-hitlist

