apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432  # This is the port your application will use to connect to the database
    targetPort: 5432  # This is the port your database is running on

apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
