apiVersion: apps/v1
kind: Deployment
metadata:
  name: scam-hitlist-7 # name of the deployment
  labels:
    app: root
    component: scam-hitlist
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: root
      component: scam-hitlist
  template:
    metadata:
      labels:
        app: root
        component: scam-hitlist
    spec:
      containers:
      - name: scam-hitlist
        image: scottlozano/scam-hitlist:latest
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: db-creds-2
              key: database-url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-creds-2
              key: username 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds-2
              key: password 
        - name: DB_NAME
          value: postgres
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: db-creds-2
              key: secret-key-base 
        ports:
        - containerPort: 8080
          name: scam-hitlist

