apiVersion: apps/v1
kind: Deployment
metadata:
  name: scam-hitlist # name of the deployment
  labels:
    app: root
    component: scam-hitlist
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: root
      component: scam-hitlist
  template:
    metadata:
      labels:
        app: root
        component: scam-hitlist
    spec:
      containers:
      - name: scam-hitlist
        image: scottlozano/scamhitlist:latest
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: database-url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: username 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: password 
        # - name: DB_NAME
        #   value: scam-hitlist-development
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: database
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: secret-key-base 
        ports:
        - containerPort: 3000
          name: scam-hitlist

