name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Bundler Audit
        run: |
          bundle audit check --update

      - name: Run Brakeman
        run: |
          gem install brakeman
          brakeman

      - name: Download OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.0/dependency-check-6.0.0-release.zip
          unzip dependency-check-6.0.0-release.zip

      - name: Run OWASP Dependency-Check
        run: |
          java -jar dependency-check/bin/dependency-check.jar --project "scam-hitlist" --out /github/workspace/owasp-reports
